name: Commit changes from main.ts to PinguinLars/Anti-Boskap's .microbit/Alarm.ts

on:
  push:
    branches:
      - main

jobs:
  commit-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Install dependencies
        run: bundle install

      - name: Copy main.ts to .microbit/Alarm.ts
        run: |
          mkdir -p .microbit
          cp main.ts .microbit/Alarm.ts

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .microbit/Alarm.ts
          git commit -m 'Update .microbit/Alarm.ts with changes from main.ts'

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push
